config/routes.rb
Rails.application.routes.draw do

  resources :tests
  root to: "tests#index"

  resources :customers
  resources :bookings, only: [:index, :new, :create, :show]
  resources :services, only: [:index, :new, :create, :show] do
    post :book, to: 'bookings#create'
    post :charge, to: 'charges#create'
    get :charge, to: 'charges#create'
  end

  resources :service_providers
  resources :customer_sessions

  resources :charges
  # # resources :charges

  # get '/login' => 'sessions#new'
  # post '/login' => 'sessions#create'
  # get '/logout' => 'sessions#destroy'


  # customer login routes
  get '/login' => 'customer_sessions#new'
  post '/login' => 'customer_sessions#create'
  get '/logout' => 'customer_sessions#destroy'
  post '/logout' => 'customer_sessions#destroy'

  # customer sigup routes
  get '/signup' => 'customers#new'
  post '/customers' => 'customers#create'

  # service provider login routes
  get '/sp-login' => 'service_provider_sessions#new'
  post '/sp-login' => 'service_provider_sessions#create'
  get '/sp-logout' => 'service_provider_sessions#destroy'
  post '/sp-logout' => 'service_provider_sessions#destroy'

  # service provicer signup routes
  get '/sp-signup' => 'service_providers#new'
  post '/service_providers' => 'service_providers#create'



  get "*missing" => "tests#404"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord

  has_many :bookings
  has_many(:services, {through: :bookings})

  # validations
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true 
  has_secure_password
  validates_uniqueness_of :email

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show

    @customer = Customer.includes(bookings: [:service]).find(params[:id])


  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: customer, local: true) do |form| %>
<% if customer.errors.any? %>
<div id="error_explanation">
  <h2 id="errorCount"><%= pluralize(customer.errors.count, "error") %> prohibited your account from being registered:</h2>
  <ul>
    <% customer.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<%= form.label :first_name %>
<%= form.text_field :first_name, class: 'form-control' %>
<%= form.label :last_name %>
<%= form.text_field :last_name, class: 'form-control' %>
<%= form.label :email %>
<%= form.text_field :email, class: 'form-control' %>
<%= form.label :password %>
<%= form.password_field :password, class: 'form-control' %>
<%= form.label :password_confirmation %>
<%= form.password_field :password_confirmation, class: 'form-control' %>
<%= form.submit "Register as customer", class: 'formButton'  %>
<% end %>

app/views/customers/_service.html.erb
<tr>
  <td>
    <%= image_tag service.img.to_s, :class => "style_image" %>
  </td>
  <td>
    <h4><%= service.title %></h4>
    <br>
    <p><h4><%= service.description %></h4></p>
  </td>
  <td>
    <h4><%= service.start_time.time.strftime("From %D at %I:%m  %p") %></h4>

  </td>
  <td>

    <h4><%= service.end_time.time.strftime("To %D at %I:%m %p") %></h4>

  </td>
  <td>
    <h4>$<%= service.price %></h4>
  </td>
</tr>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.first_name %></td>
        <td><%= customer.last_name %></td>
        <td><%= customer.email %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h2 class='registerHeader'>Register as user</h2>
<div class="newWrapper">
  <%= render 'form', customer: @customer %>
</div>

app/views/customers/show.html.erb
  <section class="orders-show">

<h2>Welcome <%= @customer.first_name%>!</h2>
<div class="black">
<div class="order-summary jumbotron">
  <div class="panel panel-default items">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th colspan="2"><h3>Services</h3></th>
        </tr>
      </thead>
      <tbody>
        <% @customer.bookings.reverse.each do |book| %>
          <%= render 'service', service: book.service %>
        <% end %>
      </tbody>

    </table>
  </div>

  <%= link_to "Continue Booking", services_path, class: 'btn btn-lg btn-primary' %>

</section>



</div>