config/routes.rb
Rails.application.routes.draw do

  resources :tests
  root to: "tests#index"

  resources :customers
  resources :bookings, only: [:index, :new, :create, :show]
  resources :services, only: [:index, :new, :create, :show] do
    post :book, to: 'bookings#create'
    post :charge, to: 'charges#create'
    get :charge, to: 'charges#create'
  end

  resources :service_providers
  resources :customer_sessions

  resources :charges
  # # resources :charges

  # get '/login' => 'sessions#new'
  # post '/login' => 'sessions#create'
  # get '/logout' => 'sessions#destroy'


  # customer login routes
  get '/login' => 'customer_sessions#new'
  post '/login' => 'customer_sessions#create'
  get '/logout' => 'customer_sessions#destroy'
  post '/logout' => 'customer_sessions#destroy'

  # customer sigup routes
  get '/signup' => 'customers#new'
  post '/customers' => 'customers#create'

  # service provider login routes
  get '/sp-login' => 'service_provider_sessions#new'
  post '/sp-login' => 'service_provider_sessions#create'
  get '/sp-logout' => 'service_provider_sessions#destroy'
  post '/sp-logout' => 'service_provider_sessions#destroy'

  # service provicer signup routes
  get '/sp-signup' => 'service_providers#new'
  post '/service_providers' => 'service_providers#create'



  get "*missing" => "tests#404"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/service_provider.rb
class ServiceProvider < ApplicationRecord

  has_many :services

  #validations
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  has_secure_password
  validates_uniqueness_of :email
  mount_uploader :img, ImgUploader
end

app/controllers/service_providers_controller.rb
class ServiceProvidersController < ApplicationController

  before_action :set_service_provider, only: [:show, :edit, :update, :destroy]


  # GET /service_providers
  # GET /service_providers.json
  def index
    @service_providers = ServiceProvider.all
  end

  # GET /service_providers/1
  # GET /service_providers/1.json
  def show


    @service_provider = ServiceProvider.find(params[:id])



    @services = @service_provider.services


  end

  # GET /service_providers/new
  def new
    @service_provider = ServiceProvider.new
    @service_provider.img = params[:service_provider][:img]

  end

  # GET /service_providers/1/edit
  def edit
  end

  # POST /service_providers
  # POST /service_providers.json
  def create
    @service_provider = ServiceProvider.new(service_provider_params)
    @service_provider.img = params[:service_provider][:img]

    respond_to do |format|
      if @service_provider.save
        format.html { redirect_to @service_provider, notice: 'Service provider was successfully created.' }
        format.json { render :show, status: :created, location: @service_provider }
      else
        format.html { render :new }
        format.json { render json: @service_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_providers/1
  # PATCH/PUT /service_providers/1.json
  def update
    respond_to do |format|
      if @service_provider.update(service_provider_params)
        format.html { redirect_to @service_provider, notice: 'Service provider was successfully updated.' }
        format.json { render :show, status: :ok, location: @service_provider }
      else
        format.html { render :edit }
        format.json { render json: @service_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_providers/1
  # DELETE /service_providers/1.json
  def destroy
    @service_provider.destroy
    respond_to do |format|
      format.html { redirect_to service_providers_url, notice: 'Service provider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_provider
      @service_provider = ServiceProvider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_provider_params
      params.require(:service_provider).permit(:first_name, :last_name, :email, :password,:img, :bio, :password_confirmation)
    end
end

app/helpers/service_providers_helper.rb
module ServiceProvidersHelper
end

app/views/service_providers/_form.html.erb
<%= form_with(model: service_provider, local: true) do |form| %>
  <% if service_provider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service_provider.errors.count, "error") %> prohibited this service provider from being saved:</h2>

      <ul>
      <% service_provider.errors.full_messages.each do |message| %>
        <li id="errorCount"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: 'form-control SP' %>



    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: 'form-control' %>



    <%= form.label :email %>
    <%= form.text_field :email, class: 'form-control' %>

     <%= form.label 'Profile picture' %>
    <%= form.file_field :img %>

    <%= form.label :bio %>
    <%= form.text_field :bio, class: 'form-control' %>

    <%= form.label :password %>
    <%= form.password_field :password, class: 'form-control' %>



    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: 'form-control' %>




  <div class="actions text-center"  >
    <%= form.submit "Register as provider", class: 'formButton'  %>
  </div>

<% end %>

app/views/service_providers/_service.html.erb
<tr>
  <td class='tableImg'>
    <%= image_tag service.img.to_s, :class => "tableImg" %>
  </td>
  <td>
    <h4><%= service.title %></h4>
    <br>
    <p><h4><%= service.description %></h4></p>
  </td>
  <td>
    <h4><%= service.start_time.time.strftime("On %D from %I:%m  %p") %></h4>

  </td>
  <td>

    <h4><%= service.end_time.time.strftime("to %I:%m %p") %></h4>

  </td>
  <td>
    <h4>$<%= service.price %></h4>
  </td>
  <td>
    <% if service.is_booked %>
    <h4 id="booked"><%= "Booked!" %></h4>
    <%else%>

    <h4 id="not"><%= "Not booked yet!" %></h4>
    <% end %>
  </td>
</tr>

app/views/service_providers/edit.html.erb
<h1>Editing Service Provider</h1>

<%= render 'form', service_provider: @service_provider %>

<%= link_to 'Show', @service_provider %> |
<%= link_to 'Back', service_providers_path %>

app/views/service_providers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Service Providers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @service_providers.each do |service_provider| %>
      <tr>
        <td><%= service_provider.first_name %></td>
        <td><%= service_provider.last_name %></td>
        <td><%= service_provider.email %></td>
        <td><%= link_to 'Show', service_provider %></td>
        <td><%= link_to 'Edit', edit_service_provider_path(service_provider) %></td>
        <td><%= link_to 'Destroy', service_provider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service Provider', new_service_provider_path %>

app/views/service_providers/new.html.erb
<h2 class="registerHeader">Register as a service provider</h2>

<div class="newWrapper">
  <%= render 'form', service_provider: @service_provider %>
</div>

app/views/service_providers/show.html.erb
<div class="black">
<section class="orders-show">



    <h2>Welcome <%= @service_provider.first_name%>!</h2>


<div class="order-summary jumbotron">
  <div class="panel panel-default items">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th colspan="2"><h3>Services</h3></th>
        </tr>
      </thead>
      <tbody>
        <% @services.each do |service| %>
          <%= render 'service', service: service %>
        <% end %>
      </tbody>
    </table>
  </div>

  <%= link_to "Create new service", new_service_path, class: 'btn btn-lg btn-primary' %>
</section>