config/routes.rb
Rails.application.routes.draw do

  resources :tests
  root to: "tests#index"

  resources :customers
  resources :bookings, only: [:index, :new, :create, :show]
  resources :services, only: [:index, :new, :create, :show] do
    post :book, to: 'bookings#create'
    post :charge, to: 'charges#create'
    get :charge, to: 'charges#create'
  end

  resources :service_providers
  resources :customer_sessions

  resources :charges
  # # resources :charges

  # get '/login' => 'sessions#new'
  # post '/login' => 'sessions#create'
  # get '/logout' => 'sessions#destroy'


  # customer login routes
  get '/login' => 'customer_sessions#new'
  post '/login' => 'customer_sessions#create'
  get '/logout' => 'customer_sessions#destroy'
  post '/logout' => 'customer_sessions#destroy'

  # customer sigup routes
  get '/signup' => 'customers#new'
  post '/customers' => 'customers#create'

  # service provider login routes
  get '/sp-login' => 'service_provider_sessions#new'
  post '/sp-login' => 'service_provider_sessions#create'
  get '/sp-logout' => 'service_provider_sessions#destroy'
  post '/sp-logout' => 'service_provider_sessions#destroy'

  # service provicer signup routes
  get '/sp-signup' => 'service_providers#new'
  post '/service_providers' => 'service_providers#create'



  get "*missing" => "tests#404"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/customer_sessions_controller.rb
class CustomerSessionsController < ApplicationController
  def new
  end

  def create
    customer = Customer.find_by(email: params[:email])
    # if the user exists AND the password entered is correct
    if customer && customer.authenticate(params[:password])
      # Save the customer id inside the browser cookie which keeps the user logged in while navigating different pages in the website
      session[:customer_id] = customer.id

      redirect_to '/'
    else
      # if user's login fails send back to user page

      redirect_to '/login', :notice => "Invalid email or password!"
    end
  end

  def destroy
    session[:customer_id] = nil
    flash[:success] = "Successfully logged out!"
    redirect_to root_path
  end
end

app/helpers/customer_sessions_helper.rb
module CustomerSessionsHelper
end

app/views/customer_sessions/_form.html.erb
    <p id="notice" class="notice2"><%= notice %></p>
    <%= form_with(url: "/login") do |form| %>
    <%= form.label :email %>
    <%= form.text_field :email, class: 'form-control' %>
    <%= form.label :password %>
    <%= form.password_field :password, class: 'form-control' %>
    <%= form.submit "Submit", class: 'formButton', id: "actions" %>
    <% end %>

app/views/customer_sessions/new.html.erb
<h2>Login</h2>




<div class="newWrapper">

<%= render 'form', customer_session: @customer_session %>


<%#= link_to 'Back', sessions_path %>

</div>